### ISSUE TITLE
Automatic dns resolver

### ISSUE THREAD

**Issue by aRandomMenno** [karasevm/PrivateDNSAndroid#1]
In the android settings there is also an option to use the dns provider provided by the network which in some cases you are required to use, which makes it better to use automatic rather than completely turning private dns off.

**Comment by karasevm** [comment]
Implemented in [Release 1.1](https://github.com/karasevm/PrivateDNSAndroid/releases/tag/v1.1).

**Comment by VellalaVineethKumar** [comment]
Hi, Thanks for the app.
I use a private DNS to block annoying ads, this is a gem 🔥.
Can you please explain more on what this "Enable Auto" function does?

**Comment by aRandomMenno** [comment]
Well I use the automatic dns resolver when I am connected to my school wifi, because that network forces you to use their dns resolver, so if you manually override that within the settings using manual dns resolver you cannot connect to the internet. Ao then I switch to automatic dns resolver to automatically use their dns resolver and when I get back home I can now immediately switch back to my nextdns profile.

If you have more questions, you can add me on discord with stackedunderflow
