### ISSUE TITLE
Labels for the urls 

### ISSUE THREAD

**Issue by binyaminyblatt** [karasevm/PrivateDNSAndroid#14]
If I have multiple urls it can be hard to identify witch one is witch it would be nice if I could name the urls so instead of displaying the url it would show the title or label witch is a label

**Comment by Fernan181** [comment]
I support this, it shouldnt be very difficult to implement and it could be an optional field, being the dns url shown if the name/label is left empty.

**Comment by karasevm** [comment]
Addresses are now stored as a simple list of strings, implementing this properly would require replacing that with something more complex. I'll take a look at which way would be the best, but don't expect it to be done tomorrow.
