### ISSUE TITLE
A feature to export and import my catalouge of DNS servers would be great

### ISSUE THREAD

**Issue by driftywinds** [karasevm/PrivateDNSAndroid#26]
### Is your feature request related to a problem? Please describe.

I frequently change devices and setting up the servers one by one again and again is a little tedious

### Describe the solution you'd like.

It would be great to have an import and export settings feature

**Comment by InfiniteCoder06** [comment]
@karasevm The why #26 is used by using clipboard which may not be ideal consider saving it to a file.

**Comment by driftywinds** [comment]
> @karasevm The why #26 is used by using clipboard which may not be ideal consider saving it to a file.

yes please

**Comment by InfiniteCoder06** [comment]
> @InfiniteCoder06 In my experience I find saving/restoring data from clipboard easier and more flexible. Most users' configs will be under 200 characters, which fits in most messenger apps and can be saved anywhere where you can store text.

What if we set up in other device, May be we implement both the ways?

**Comment by karasevm** [comment]
@InfiniteCoder06 Good idea, I've just made them sub-menus with all possible export/import options.
