### ISSUE TITLE
Unable to grant write permissions throughout ADB

### ISSUE THREAD

**Issue by xulqarnaen** [karasevm/PrivateDNSAndroid#28]
I've followed every step but when I enter the command, it says " ' . ' is not recognised as an internal or external command, operable program or batch file."

Im running an aosp based custom rom, PixelOS

**Comment by Mujtaba0150** [comment]
Try "adb.exe shell pm grant ru.karasevm.privatednstoggle android.permission.WRITE_SECURE_SETTINGS" if you're using cmd instead of Powershell

**Comment by karasevm** [comment]
@xulqarnaen Did the steps provided by @Mujtaba0150 help? Another way that should work is to run `powershell` before running the provided command.

**Comment by xulqarnaen** [comment]
@karasevm yes, thanks it worked.
