### ISSUE TITLE
Disable DNS server

### ISSUE THREAD

**Issue by Quiter** [karasevm/PrivateDNSAndroid#31]
### Is your feature request related to a problem? Please describe.

Hey, please add an option to disable DNS server in the list. I have a few server but will use some of them only if one of them is not working. So it would be very useful to disable them in the list instead of deleting them.

### Describe the solution you'd like.

Split the list and make the upper part for the enabled server und the lower part for the disabled server. It could work very well withe the drag and drop sorting.

**Comment by karasevm** [comment]
@InfiniteCoder06 I'm currently in the process of refactoring the sever storage backend, so it's would probably be better for you to wait for that.

**Comment by InfiniteCoder06** [comment]
@karasevm This can be closed?

**Comment by sebtech33** [comment]
Are there any updates on this? I would really like this feature too.

**Comment by karasevm** [comment]
Implemented in [v1.9.0](https://github.com/karasevm/PrivateDNSAndroid/releases/tag/v1.9.0).
