### ISSUE TITLE
Excluding Apps

### ISSUE THREAD

**Issue by The1MHR** [karasevm/PrivateDNSAndroid#34]
### Is your feature request related to a problem? Please describe.

If there was a option to exclude some apps that I don't to filter that particular app except the rest.

### Describe the solution you'd like.

Please implement this option

**Comment by karasevm** [comment]
Sadly not possible, this app uses Android's built-in DNS-over-TLS feature, which controls the DNS server for the whole system. And while automated server switching is something I am considering, changing the server on every app open/close does not seem like a good solution and falls apart completely if the excluded app tries to fetch something in the background. As an alternative you can use [DNS66](https://github.com/julian-klode/dns66) that allows bypassing the blocking for specified apps by routing all DNS requests through a local on-device VPN service.
