### ISSUE TITLE
Unable to add dns server

### ISSUE THREAD

**Issue by tristan-k** [karasevm/PrivateDNSAndroid#39]
For unkown reasons I'm unable to create add a dns server in the settings. See this screen recording for further information:

https://github.com/user-attachments/assets/35aff4e7-fd03-4982-970c-48fd64818fb9

I suspect it could be related to another app which overlays on the screen and blocks the ui.

**Comment by stephenvaz** [comment]
Android's Private DNS feature requires the hostname and not the IP of the DNS server.

You can find the hostname for a DNS provider usually on their website. In the case of Cloudflare's 1.1.1.1, the hostname is `one.one.one.one`.

If you want to use your own DNS server, you could manually edit the Wi-Fi config for your home Wi-Fi to use that specific DNS when connected to it in the Wi-Fi settings

**Comment by tristan-k** [comment]
Thanks for the heads-up. Is this generally not possible or is this specific to `PrivateDNSAndroid´? On OneUI 6.1 (Android 14) it's not possible to add custom dns server in the Wi-Fi settings.

**Comment by karasevm** [comment]
Thanks to #9 we validate the input fields the exact same way as AOSP, so I'd assume anything not accepted is generally not supported.    
As a solution for the home network you can either set the DNS through the DHCP server option 6, as @stephenvaz has already mentioned, or you can switch to a DNS server that supports DoT such as [AdGuardHome](https://github.com/AdguardTeam/AdGuardHome).    
I'm going to close the issue, but if you have any questions regarding the proposed solutions feel free to ask.
