### ISSUE TITLE
DNS not getting toggled

### ISSUE THREAD

**Issue by idogadol** [karasevm/PrivateDNSAndroid#41]
### Application Version

1.9.0

### Application Version

14

### Device

Samsung Galaxy S24+

### How do you provide the permission?

ADB

### What happened?

I followed the instructions to make the app work and not just send me to the GitHub page, added dns.adguard-dns.com to the app, and enabled it.

Unfortunately, it does not work, toggling the server to Enabled does not truly enable it, and when I look in my phone's Settings>Connections>More connection settings>Private DNS, the DNS is disabled.

**Comment by idogadol** [comment]
![Screenshot_20241111_152007_Private DNS Quick Toggle](https://github.com/user-attachments/assets/9f35cd6e-ef04-4b96-a1d7-4ad8a085c1f0)

You are correct, it changes in the app but not in system settings. 

If it's disabled in system settings and I enable it through the app, it does not get enabled.

If it's enabled in the system settings, it will still appear disabled in the app.

If it's disabled in both system settings and the app, enabling it in one will not enable it in the other.

If it's enabled in both system settings and the app, disabling it in one will not disable in the other.

**Comment by karasevm** [comment]
I am sorry, but do you mean the switch in the server options when you say you "Enabled" it? The app is a quick tile that you must add in your quick panel, and the "Enable" switch only affects which servers are included in the cycle when tapping the tile.

**Comment by karasevm** [comment]
<details>

<summary>I've recorded a video showing how it works on S24+</summary>

https://github.com/user-attachments/assets/a9b4239b-bcfb-4675-86df-c70457b7e442
</details>

**Comment by idogadol** [comment]
> I've recorded a video showing how it works on S24+

Thank you!!!!
I'm sorry, I completely misunderstood how it works, it's far more convenient than I expected, I thought I had to open the "Private DNS Quick Toggle" app, tap the server I added, and then enable/disable it, I super appreciate the help and tutorial!
