### ISSUE TITLE
Can't add server

### ISSUE THREAD

**Issue by aagha** [karasevm/PrivateDNSAndroid#44]
### Application Version

1.9.0

### Application Version

15

### Device

Pixel 7a

### How do you provide the permission?

Shizuku

### What happened?

I allowed access in Shizuku but going to the app forwarded me to the github page so I also provided access with adb

![image](https://github.com/user-attachments/assets/986fe79d-8b18-48df-947f-b917dd5592ec)

Trying to add a server keeps the Add button from being submitted:

![image](https://github.com/user-attachments/assets/85c7880a-ebe0-43ad-bbf3-2b8fb4aa8389)

**Comment by karasevm** [comment]
Android requires a hostname not an IP address and the app uses the same logic as the system settings. For the default Cloudflare resolver you can use `one.one.one.one`, as described in [their documentation](https://developers.cloudflare.com/1.1.1.1/setup/android/#android-11-or-later).
