### ISSUE TITLE
Add an toggle to disable the "Off" option and show "Auto" as a turned off tile

### ISSUE THREAD

**Issue by Fernan181** [karasevm/PrivateDNSAndroid#5]
I don't use the "Off" option as I don't think it makes any sense having the "Auto" option provided by #1 so it just makes me having to tap more times to switch to the option i want. Could we have an option to disable it?

Also, in line with this kind of usage of the app, another option that could allowed you to show the "Auto" option as a turned off tile instead of a turned on one would make it more visual and add a bit more of customization to the app.

**Comment by Fernan181** [comment]
Sorry, misclicked the close button 😅

**Comment by gitterspec** [comment]
Same here. Having to cycle through off when it's not needed is also unsecure.

**Comment by Crunchbits** [comment]
This would definitely be a good idea. At the very least just an option to remove "off".

**Comment by karasevm** [comment]
Implemented in [Release 1.3](https://github.com/karasevm/PrivateDNSAndroid/releases/tag/v1.3).
