### ISSUE TITLE
Sometimes after clicking on a tile nothing happens

### ISSUE THREAD

**Issue by Artem13327** [karasevm/PrivateDNSAndroid#7]
This is already the second similar application where I encounter this oddity, and I have to switch the private DNS settings in the settings and it seems to help
It also happens that something seems to happen after a while, well, in general, I don’t know how to explain it

**Comment by karasevm** [comment]
Please provide more information: phone maker, model, android version. Also if you are able/willing to provide logs that would be very helpful as well.

**Comment by njascgil** [comment]
At first, I also tought that was the issue. But then it ocurred to me that it might be cycling through the DNS servers I had entered.
After checking Android settings, that was indeed the case: pressing the tile cycles between servers, but only notifies when turning on, not when just changing to another server.

**Comment by njascgil** [comment]
With the latest version (1.7) the issue described in my previous post still appears on my Poco X5 Pro.
Please let me know if I should try to provide more details or if it would be better to open a new issue.

**Comment by karasevm** [comment]
Sorry for taking so long to follow up. The screen recording was really useful, the messages that appear on top is something done by MIUI/HyperOS itself and is not something the app can control. You can enable icon labels to get the intended behavior by going into Settings -> Notifications & status bar and toggling off "Don't show icon labels".
